<robot name="my_car_move" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- Transmission implementation: for connecting the controller to the joint -->
    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- each drive wheel needs to be equipped with a transmission -->
    <xacro:joint_trans joint_name="front_left_wheel" />
    <xacro:joint_trans joint_name="front_right_wheel" />
    <xacro:joint_trans joint_name="rear_left_wheel" />
    <xacro:joint_trans joint_name="rear_right_wheel" />

    <!-- controller -->
    <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <updateRate>100.0</updateRate>
            <robotNamespace>/</robotNamespace>
            <leftFrontJoint>front_left_wheel</leftFrontJoint> <!-- left front wheel -->
            <rightFrontJoint>front_right_wheel</rightFrontJoint> <!-- right front wheel -->
            <leftRearJoint>rear_left_wheel</leftRearJoint> <!-- left back wheel -->
            <rightRearJoint>rear_right_wheel</rightRearJoint> <!-- right back wheel -->
            <wheelSeparation>${track}</wheelSeparation> <!-- wheel spacing -->
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter> <!-- wheel diameter -->
            <robotBaseFrame>base_footprint</robotBaseFrame> <!-- base frame -->
            <torque>50</torque>
            <topicName>cmd_vel</topicName> <!-- motion control topic -->
            <broadcastTF>true</broadcastTF>
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> <!-- odometer topics -->
            <robotBaseFrame>base_footprint</robotBaseFrame> <!-- robot base frame -->
        </plugin>
    </gazebo>

</robot>